name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: isaacdemoapp.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        cd mydemoapp
        docker build . -t isaacdemoapp.azurecr.io/isaacdemoapp:${{ github.sha }}
        docker push isaacdemoapp.azurecr.io/isaacdemoapp:${{ github.sha }}     

    - name: Azure Login
      uses: Azure/login@v1.6.1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'isaacdemoapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'isaacdemoapp.azurecr.io/mydemoapp:${{ github.sha }}'
